#!/bin/bash

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"

# rofi theme
theme="$HOME/.config/rofi/themes/power_menu.rasi"
confirm_theme="$HOME/.config/rofi/themes/confirm.rasi"

# Get user confirmation 
get_confirmation() {
	rofi -dmenu -i -monitor -1 \
		 -no-fixed-num-lines \
		 -p "Are you sure? : " \
		 -theme "$confirm_theme" 
		 
}


get_options() {
  echo "   Poweroff"
  echo "   Reboot"
  echo "   Lock"
  echo "   Suspend"
  echo "   Logout"
}

main() {

  # get choice from rofi
  choice=$( (get_options) | rofi -show -dmenu -p "" -i -theme "$theme")

  # run the selected command
  case $choice in
  '   Poweroff')
	systemctl poweroff
    ;;
  '   Reboot')
 	systemctl reboot
    ;;
  '   Lock')
      hyprlock
    ;;
  '   Suspend')
    	mpc -q pause
	amixer set Master mute
	betterlockscreen --suspend
    ;;
  '   Logout')
	hyprctl dispatch
    ;;
  esac

  # done
  set -e
}

main &

exit 0

